### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dgoetz** [svenfuchs/safemode#33]
May I kindly ask for a new release including the fix from my pull request and the other changes? I want to have it in Foreman and a new release would be preferred over a snapshot version. Thanks in advance!

**Comment by ehelms** [comment]
@ohadlevy @dmitri-d I know y'all are a bit removed these days from the project, but if you were able to do address this release request @theforeman would appreciate it!

**Comment by kronn** [comment]
I just checked and it seems I have the permissions to do such a release. I will try to do that in the coming days.

**Comment by kronn** [comment]
I am sorry that I took so long, life and all... 

I present you: safemode 1.3.6, which is essentially current master, since that included the change you wanted. I also updated the travis.yml to result in a green build:

- https://rubygems.org/gems/safemode/versions/1.3.6
- https://travis-ci.org/github/svenfuchs/safemode/builds/722711041

**Comment by kronn** [comment]
One question pops into my mind, @ekohl @dgoetz : Which ruby-version(s) does foreman install/use/support? Since foreman/satellite is a major user of safemode, I see this information as a important datapoint. Also, something I want to know before trimming away older and unsupported rubies from the build-matrix. If there is OTOH an installation base that still uses older Ruby-Version with SCL-Securitypatches, I would need to tweak the tests and implementation to also run on that, right?

**Comment by ekohl** [comment]
At this moment we use 2.5 or later everywhere. From a Foreman point of view, we no longer care about Ruby 2.4 and older. I think the SCLs don't really carry patches and we don't do any special testing. AFAIK our CI uses RVM to install a Ruby 2.5. Debian 10 and Ubuntu 18.04 also ship Ruby 2.5.
